In [6]:
#10 elemanlı bir sıfır dizisi oluştur
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#1'den 100'e kadar olan sayilardan bir dizi olustur
arr=np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
#bir önceki dizinin ortalamsını hesapla
np.mean(arr)

50.5

In [28]:
#10 elemanlı rastgele dizi olustur ve her elemanını 2 ile carp
arr2=np.random.randint(1,11,10)
arr2



array([ 6,  7,  5,  2, 10,  4,  8,  4,  2,  3])

In [29]:
arr2*2

array([12, 14, 10,  4, 20,  8, 16,  8,  4,  6])

In [32]:
#bir diziden 3 e 3 lük bir matris olustur
arr3=np.random.randint(1,11,9)
arr3

array([ 1,  6,  2,  6,  3,  7,  8,  1, 10])

In [33]:
arr3.reshape(3,3)

array([[ 1,  6,  2],
       [ 6,  3,  7],
       [ 8,  1, 10]])

In [34]:
#5e 5 boyutunda rastgele sayilardan olusan bir matris olustur
matrix=np.random.randint(0,11,(5,5))
matrix

array([[ 8,  6,  7,  2,  6],
       [ 8,  0,  1,  3,  2],
       [ 9,  9,  1,  5,  7],
       [ 0,  0,  1,  2,  8],
       [10,  1,  4,  2,  8]])

In [35]:
#bir önceki matristeki en büyük ve en küçük değerleri bul
np.min(matrix)

0

In [36]:
np.max(matrix)

10

In [37]:
# 3 e 3 lük 2 matris olustur ve birbiriyle carp(normalde olan matris carpımını da yapacagım)
matrix1=np.random.randint(0,101,(3,3))
matrix2=np.random.randint(0,201,(3,3))
matrix1

array([[40, 10, 79],
       [25, 98, 60],
       [51, 82, 60]])

In [38]:
matrix2

array([[158,  12, 177],
       [147, 158,  58],
       [ 33, 181,   1]])

In [39]:
matrix1*matrix2


array([[ 6320,   120, 13983],
       [ 3675, 15484,  3480],
       [ 1683, 14842,    60]])

In [40]:
matrixproduct=matrix1@matrix2
matrixproduct


array([[10397, 16359,  7739],
       [20336, 26644, 10169],
       [22092, 24428, 13843]])

In [42]:
#1'den 25'e kadar olan sayıları bir diziye 5-5 bir matrise cevir ve 3.satırı al
arr4=np.arange(1,26)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [55]:
matrix3=arr4.reshape(5,5)
matrix3


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
thirdcolum=matrix3[:,2:3]
thirdcolum

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [59]:
#5-5 bir matrisin sadece köşelerindeki elemanları al
arr5=([matrix[0,0],matrix[0,4],matrix[4,0],matrix[4,4]])
arr5

[8, 6, 10, 8]

In [60]:
#10 elemanlı bir dizi olustur ve sadece 5ten büyük olanları sec
arr6=np.random.randint(0,11,10)
arr6

array([8, 7, 3, 2, 9, 2, 0, 8, 7, 6])

In [61]:
arr6[arr6>5]

array([8, 7, 9, 8, 7, 6])

In [62]:
#4-4lük bir matris olustur ve cift sayıları sıfır yap
matrix4=np.random.randint(0,21,(4,4))
matrix4

array([[15, 20,  4,  5],
       [ 4, 20, 14,  5],
       [13, 12,  9, 10],
       [14, 13,  1,  5]])

In [63]:
matrix4[matrix4%2==0]=0
matrix4

array([[15,  0,  0,  5],
       [ 0,  0,  0,  5],
       [13,  0,  9,  0],
       [ 0, 13,  1,  5]])

In [64]:
#100 elelmanlı rastgele bir dizi oluştur ve standart sapmasını hesapla
hundred=np.random.randint(0,101,100)
hundred


array([ 8, 75, 14, 69, 63, 75, 38, 98, 37, 89, 10, 83, 39, 62, 61, 34, 51,
       52, 18, 38, 39, 97, 41, 97, 39, 80, 27, 12, 13, 63, 18,  7,  7, 87,
       82, 98, 23, 86, 23, 55, 14, 92, 30, 98, 76, 83, 68, 89, 73, 88, 28,
       47, 55, 61, 48, 84, 87, 98, 80, 11, 70,  3, 77, 14, 13, 49, 92, 25,
       20, 52, 89, 77, 28, 73, 33, 87, 76, 68, 65, 92, 48, 56, 91, 50, 68,
       11, 11, 28, 19, 27, 66, 43, 27, 86, 42, 12, 49, 24, 86, 26])

In [65]:
np.std(hundred)

28.927528411532155

In [66]:
#6-6lık bir matrisin satır bazında ortalamalarını bul
matrix5=np.random.randint(0,21,(6,6))
matrix5

array([[ 2,  9, 12,  2, 12, 11],
       [ 5,  3,  3,  6,  6, 10],
       [17, 13,  7,  1, 16, 17],
       [17,  5,  6,  8,  9, 12],
       [10,  7, 11,  5,  2, 15],
       [ 1,  7,  5, 12, 14,  7]])

In [67]:
np.mean(matrix5,axis=1)

array([ 8.        ,  5.5       , 11.83333333,  9.5       ,  8.33333333,
        7.66666667])

In [70]:
#arange linscape logspace il dizi olusturma
arr7=np.linspace(0,100,5)
arr7

array([  0.,  25.,  50.,  75., 100.])

In [71]:
arr8=np.arange(0,10001)
arr8

array([    0,     1,     2, ...,  9998,  9999, 10000])

In [77]:
arr9=np.logspace(0,2,10)
arr9

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [78]:
#5-5lik bir matris olustur ve her sütunun en büyük elemanını bul
matrix6=np.random.randint(0,21,(5,5))
matrix6

array([[15,  6,  1,  0, 14],
       [ 3, 16, 17, 20,  1],
       [ 4, 10, 14, 20, 18],
       [14, 18,  7,  8,  3],
       [ 7, 13,  0, 11, 17]])

In [80]:
np.max(matrix6,axis=0)

array([15, 18, 17, 20, 18])

In [99]:
#8-8lik bir matris olustur ve sütun numarası cift olanları 0 yap
matrix7=np.random.randint(0,51,(8,8))
matrix7

array([[39, 43, 25,  2,  3, 38, 48, 46],
       [10, 49, 13, 42, 16, 33, 24, 10],
       [17,  3, 18,  1, 42, 10, 45,  3],
       [22, 34, 36, 40, 27, 17, 46, 41],
       [34, 46, 24, 31, 33, 39, 13, 33],
       [ 2, 12, 21,  4,  0, 14, 47, 13],
       [29, 18, 18, 36, 36, 24, 30, 21],
       [21, 19, 19, 21,  1, 32, 45, 34]])

In [102]:
matrix7[:,::2]=0
matrix7

array([[ 0, 43,  0,  2,  0, 38,  0, 46],
       [ 0, 49,  0, 42,  0, 33,  0, 10],
       [ 0,  3,  0,  1,  0, 10,  0,  3],
       [ 0, 34,  0, 40,  0, 17,  0, 41],
       [ 0, 46,  0, 31,  0, 39,  0, 33],
       [ 0, 12,  0,  4,  0, 14,  0, 13],
       [ 0, 18,  0, 36,  0, 24,  0, 21],
       [ 0, 19,  0, 21,  0, 32,  0, 34]])